// Page patterns: the team's real pages (e.g. Figma frames) as A2UI structure + example data.
// Source of truth: <a2ui dir>/patterns/<name>.json (read by the agent).
// This module lints them, validates them against the catalog, and generates one Storybook
// story per pattern under "A2UI Patterns/<Name>" so people see what the agent follows.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { checkRun } from "./check.mjs";

const REQUIRED = ["name", "whenToUse", "components", "exampleData"];

export function loadPatterns(dir) {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => ({
      file: f,
      path: join(dir, f),
      pattern: JSON.parse(readFileSync(join(dir, f), "utf8")),
    }));
}

/** Structural problems in a pattern file. */
export function lintPattern(p) {
  const problems = REQUIRED.filter((k) => p[k] === undefined).map(
    (k) => `missing "${k}"`,
  );
  if (p.name && !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(p.name))
    problems.push(`name "${p.name}" must be kebab-case`);
  if (Array.isArray(p.components) && !p.components.some((c) => c.id === "root"))
    problems.push('no component with id "root"');
  if (typeof p.whenToUse === "string" && /^\s*TODO/i.test(p.whenToUse))
    problems.push(
      '"whenToUse" is still a TODO — describe the job this page does and its regions',
    );
  else if (typeof p.whenToUse === "string" && p.whenToUse.length < 40)
    problems.push(
      '"whenToUse" is too short — describe the page and its regions so an agent can choose it',
    );
  if (!p.source)
    problems.push('no "source" — record the design file/node it came from');
  return problems;
}

/** The pattern as an A2UI message stream, rendered with its own example data. */
export function patternMessages(p, catalogId) {
  return [
    { version: "v0.9", createSurface: { surfaceId: p.name, catalogId } },
    {
      version: "v0.9",
      updateComponents: { surfaceId: p.name, components: p.components },
    },
    {
      version: "v0.9",
      updateDataModel: { surfaceId: p.name, path: "/", value: p.exampleData },
    },
  ];
}

/** Schema/refs/bindings/guardrail check of a pattern, same rules as runs. */
export function validatePattern(p, catalog, guardrails = {}) {
  // Size limits exist to stop an agent over-building; a real designed page may exceed them.
  // For patterns they become calibration warnings instead of errors.
  const { maxDepth, maxComponents, ...rules } = guardrails;
  const r = checkRun(
    { messages: patternMessages(p, catalog.id) },
    catalog,
    rules,
  );
  if (maxDepth && r.depth > maxDepth)
    r.warnings.push(
      `size: this real page nests ${r.depth} deep but guardrail maxDepth is ${maxDepth} — agent pages like it would fail; raise it if this page is typical`,
    );
  if (maxComponents && r.count > maxComponents)
    r.warnings.push(
      `size: this real page has ${r.count} components but guardrail maxComponents is ${maxComponents} — raise it if this page is typical`,
    );
  return r;
}

const pascal = (s) => s.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());
const title = (s) =>
  s.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

function figmaUrl(source) {
  if (!source?.figmaFile) return null;
  const node = source.node
    ? `?node-id=${String(source.node).replace(":", "-")}`
    : "";
  return `https://www.figma.com/design/${source.figmaFile}/${node}`;
}

/** One CSF file per pattern: "A2UI Patterns/<Name>", importing the JSON so edits show live. */
export function writePatternStories(
  list,
  {
    outDir,
    playgroundImport = "./A2uiPlayground",
    schemaImport = "./catalog.schema",
  },
) {
  mkdirSync(outDir, { recursive: true });
  return list.map(({ path, pattern: p }) => {
    const outFile = join(outDir, `A2UI.Pattern.${pascal(p.name)}.stories.tsx`);
    const jsonImport = `./${relative(dirname(outFile), path).split("\\").join("/")}`;
    const url = figmaUrl(p.source);
    const limits = (p.notExpressible ?? []).map((x) => `- ${x}`).join("\\n");
    const doc = [
      `**When to use:** ${p.whenToUse}`,
      url ? `**Source:** [${p.source.frame ?? p.source.node}](${url})` : null,
      limits ? `**Not expressible with this catalog yet:**\\n${limits}` : null,
      "_Agents read the JSON file; this story renders it with its example data._",
    ]
      .filter(Boolean)
      .join("\\n\\n")
      .replace(/`/g, "\\`");
    writeFileSync(
      outFile,
      `// GENERATED by storybook-a2ui (\`a2ui.mjs patterns\`) — edit ${jsonImport}, not this file.
import React from 'react';
import { A2uiPlayground, type A2uiRun } from '${playgroundImport}';
import { CATALOG_ID } from '${schemaImport}';
import pattern from '${jsonImport}';

const run: A2uiRun = {
  prompt: pattern.whenToUse,
  dataset: 'example',
  messages: [
    { version: 'v0.9', createSurface: { surfaceId: pattern.name, catalogId: CATALOG_ID } },
    { version: 'v0.9', updateComponents: { surfaceId: pattern.name, components: pattern.components } },
    { version: 'v0.9', updateDataModel: { surfaceId: pattern.name, path: '/', value: pattern.exampleData } },
  ],
};

export default {
  title: 'A2UI Patterns/${title(p.name)}',
  tags: ['a2ui-pattern'],
  parameters: {
    layout: 'padded',
    chromatic: { disableSnapshot: true },
    docs: { description: { component: \`${doc}\` } },
  },
};

export const Example = { render: () => <A2uiPlayground run={run} /> };
`,
    );
    return outFile;
  });
}
