// Generate one CSF stories file per scenario from runs/<scenario>--<dataset>.json.
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, dirname } from "node:path";

const pascal = (s) =>
  s
    .replace(/(^|[-_\s]+)(\w)/g, (_, __, c) => c.toUpperCase())
    .replace(/\W/g, "");
const title = (s) =>
  s.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

export function groupRuns(runsDir) {
  const groups = new Map();
  for (const file of readdirSync(runsDir)
    .filter((f) => f.endsWith(".json"))
    .sort()) {
    const [scenario, dataset = "default"] = file
      .replace(/\.json$/, "")
      .split("--");
    if (!groups.has(scenario)) groups.set(scenario, []);
    groups.get(scenario).push({ file, dataset });
  }
  return groups;
}

export function writeStories({
  runsDir,
  outDir,
  playgroundImport = "./A2uiPlayground",
  section = "A2UI Playground",
}) {
  const written = [];
  for (const [scenario, runs] of groupRuns(runsDir)) {
    const outFile = join(outDir, `A2UI.${pascal(scenario)}.stories.tsx`);
    const rel = (f) =>
      `./${relative(dirname(outFile), join(runsDir, f)).split("\\").join("/")}`;
    const imports = runs
      .map((r, i) => `import run${i} from '${rel(r.file)}';`)
      .join("\n");
    const exports = runs
      .map(
        (r, i) =>
          `export const ${pascal(r.dataset)} = story(run${i} as A2uiRun);`,
      )
      .join("\n");
    writeFileSync(
      outFile,
      `// GENERATED by storybook-a2ui — do not edit; re-run \`a2ui.mjs stories\`.
import React from 'react';
import { A2uiPlayground, type A2uiRun } from '${playgroundImport}';
${imports}

export default {
  title: '${section}/${title(scenario)}',
  // Playground output, not a component contract: keep it out of Chromatic visual tests.
  parameters: { layout: 'padded', chromatic: { disableSnapshot: true } },
};

const story = (run: A2uiRun) => ({
  render: () => <A2uiPlayground run={run} showMeta />,
  parameters: {
    docs: {
      description: { story: \`**Prompt:** \${run.prompt} · **Dataset:** \${run.dataset}\` },
      // "Show code" displays the agent's A2UI output, not the story wrapper.
      source: { code: JSON.stringify(run.messages, null, 2), language: 'json' },
    },
  },
});

${exports}
`,
    );
    written.push({ outFile, stories: runs.map((r) => r.dataset) });
  }
  return written;
}
