// GENERATED by storybook-a2ui — do not edit; re-run `a2ui.mjs stories`.
import React from 'react';
import { A2uiPlayground, type A2uiRun } from './A2uiPlayground';
import run0 from './runs/flights--empty.json';
import run1 from './runs/flights--few.json';
import run2 from './runs/flights--many.json';

export default {
  title: 'A2UI Playground/Flights',
  // Playground output, not a component contract: keep it out of Chromatic visual tests.
  parameters: { layout: 'padded', chromatic: { disableSnapshot: true } },
};

const story = (run: A2uiRun) => ({
  render: () => <A2uiPlayground run={run} showMeta />,
  parameters: {
    docs: {
      description: { story: `**Prompt:** ${run.prompt} · **Dataset:** ${run.dataset}` },
      // "Show code" displays the agent's A2UI output, not the story wrapper.
      source: { code: JSON.stringify(run.messages, null, 2), language: 'json' },
    },
  },
});

export const Empty = story(run0 as A2uiRun);
export const Few = story(run1 as A2uiRun);
export const Many = story(run2 as A2uiRun);
